# Generated by Django 5.2.5 on 2025-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='cars/videos/')),
            ],
        ),
    ]
