# Generated by Django 5.2.5 on 2025-08-30 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кузов')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Состояние')),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Топливо')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(verbose_name='Минимальная цена')),
                ('max_price', models.IntegerField(verbose_name='Максимальная цена')),
            ],
        ),
        migrations.AddField(
            model_name='carcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cars/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.bodytype', verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.condition', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.fueltype', verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='price_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.pricerange', verbose_name='Диапазон цен'),
        ),
    ]
