# Generated by Django 5.2.5 on 2025-08-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_bodytype_color_condition_fueltype_pricerange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcontent',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('wagon', 'Универсал'), ('suv', 'Внедорожник (SUV)'), ('crossover', 'Кроссовер'), ('coupe', 'Купе'), ('convertible', 'Кабриолет'), ('pickup', 'Пикап'), ('minivan', 'Минивэн')], max_length=15),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный'), ('gray', 'Серый'), ('silver', 'Серебристый'), ('blue', 'Синий'), ('red', 'Красный'), ('green', 'Зеленый'), ('yellow', 'Желтый'), ('brown', 'Коричневый'), ('orange', 'Оранжевый'), ('purple', 'Фиолетовый'), ('gold', 'Золотой')], max_length=10),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=10),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('gas', 'Газ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='price_range',
            field=models.CharField(choices=[('5000-10000', '5000$ - 10000$'), ('10000-15000', '10000$ - 15000$'), ('15000-20000', '15000$ - 20000$'), ('20000-25000', '20000$ - 25000$'), ('25000-30000', '25000$ - 30000$'), ('30000-35000', '30000$ - 35000$'), ('35000-40000', '35000$ - 40000$'), ('40000-45000', '40000$ - 45000$'), ('45000-50000', '45000$ - 50000$'), ('50000-60000', '50000$ - 60000$')], max_length=15),
        ),
        migrations.RemoveField(
            model_name='carcontent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='carcontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carcontent',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cars/videos/'),
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='PriceRange',
        ),
    ]
