# Generated by Django 5.2.5 on 2025-09-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_carcontent_body_type_alter_carcontent_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcontent',
            name='photo',
        ),
        migrations.AddField(
            model_name='carcontent',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos1/'),
        ),
        migrations.AddField(
            model_name='carcontent',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos2/'),
        ),
        migrations.AddField(
            model_name='carcontent',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos3/'),
        ),
        migrations.AddField(
            model_name='carcontent',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos4/'),
        ),
        migrations.AddField(
            model_name='carcontent',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos5/'),
        ),
    ]
