# Generated by Django 5.2.5 on 2025-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_carcontent_photo_carcontent_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcontent',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
